### ISSUE TITLE
Unity 2019, cubes not spawning, need a little bit of help for a non-ECS user

### ISSUE THREAD

**Issue by PrakashNep** [kakunpc/UnityECSSample#1]
Hello. I am trying to do some performance testings related for my game and which way to work on it, and ECS seems really performant as everyone says. For now I don't know much about how someone writes in ECS, and @kakunpc this sample project is really helpful tbh and the code doesn't seem much of a headache when learned properly. But for my tests, I'm on Unity 2019.2.18f1, and as of currently, the sample project isn't spawning any cubes. 
There has been many changes to the ECS system since the time this sample project was made. I had to change "MeshInstanceRenderer" to "RenderMesh" to get rid of the errors. But still as I said, the cubes aren't spawning and I really wish the author of this project could help with it. It would be very very helpful :) 
Kind regards.
- Neon.

Edit: And I did try to set the mesh myself to a model I had, and instead of the OVRCamera I put a default Camera. The overall the code looks good and I don't know where the problem is. Any help is very appreciated.

**Comment by kakunpc** [comment]
Updated to `Unity 2019.3.0f5` and `Entity preview. 17 - 0.5.0`
Thx!

**Comment by PrakashNep** [comment]
Thank you so so much :) (big smiley)
Will be very helpful :) :smiley:
